name: client
options:
  bundleIdPrefix: com.interlinq
  deploymentTarget:
    iOS: 14.0
  generateEmptyDirectories: true
  postGenCommand: pod install
targets:
  client:
    platform: iOS
    type: application
    sources:
      - Sources/
      - .gitignore
      - README.md
      - project.yml

